name: flame3-submission
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.18
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - numpy=1.26.0
  - pillow=9.4.0
  - pyyaml=6.0
  - matplotlib=3.5.3
  - pandas=1.5.3
  - pip=23.2.1
  - pip:
      - scipy==1.11.3
      - opencv-python==4.8.1.78
      - thop==0.1.1.post2209072238
